db:
  host: "127.0.0.1"
  port: 27017
  username: "magic"
  password: "isintheair"
messages:
  chatformat: "&7%s &8⇒ &7%s"
  prefix: "&7[&5Magic&6Wars&7] "
  playerjoin: "&a⇨ &7%p &ahat das Spiel betreten"
  playerquit: "&c⇦ &7%p &chat das Spiel verlassen"
  playerdeath: "&c%p &7wurde getötet von &a%k"
  gamestart: "&aLasst die Spiele beginnen!"
  peaceend: "&cWarmup-Phase ist nun beendet."
  deathmatchstart: "&aDas Deathmatch beginnt nun."
  winner: "&c%p &7hat das Spiel gewonnen"
minplayers: 2
worldbordersize: 160