db:
  host: "127.0.0.1"
  port: 27017
  username: "magic"
  password: "isintheair"
messages:
  chatformat: "%s => %s"
  prefix: "[MagicWars] "
  playerjoin: "%p joined the game"
  playerquit: "%p left the game"
  gamestart: "Game starts in %t Seconds"
  deathmatchstart: "Deathmatch begins in %t Seconds"
  playerdeath: "%p was killed by %k"
  gamestart: "Let the games begin!"
  peaceend: "Warumup ended now."
  deathmatchstart: "The Deathmatch begins now."
minplayers: 4