db:
  host: "127.0.0.1"
  port: 27017
  username: "magic"
  password: "isintheair"
messages:
  chatformat: "&7%s &8⇒ &7%s"
  prefix: "&7[&5Magic&6Wars&7] "
  playerjoin: "&a⇨ &7%p &ajoined the game"
  playerquit: "&c⇦ &7%p &cleft the game"
  gamestart: "&eGame &7starts in &e%t &7Seconds"
  deathmatchstart: "&eDeathmatch &7begins in &e%t &7seconds"
  playerdeath: "&c%p &7was killed by &a%k"
  gamestart: "&aLet the games begin!"
  peaceend: "&cWarmup ended now."
  deathmatchstart: "&aThe deathmatch begins now."
  winner: "&c%p &7won the game"
minplayers: 2
worldbordersize: 160